const constants = {
    ADD_ITEM_TO_CART_START: 'ADD_ITEM_TO_CART_START',
    ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
    ADD_ITEM_TO_CART_FALIURE: 'ADD_ITEM_TO_CART_FALIURE',

    UPDATE_CART_ITEM_START: `UPDATE_CART_ITEM_START`,
    UPDATE_CART_ITEM_SUCCESS: `UPDATE_CART_ITEM_SUCCESS`,
    UPDATE_CART_ITEM_FALIURE: `UPDATE_CART_ITEM_FALIURE`,

    DELETE_CART_ITEM_START: `DELETE_CART_ITEM_START`,
    DELETE_CART_ITEM_SUCCESS: `DELETE_CART_ITEM_SUCCESS`,
    DELETE_CART_ITEM_FALIURE: `DELETE_CART_ITEM_FALIURE`,

    CLEAR_CART_START: `CLEAR_CART_START`,
    CLEAR_CART_SUCCESS: `CLEAR_CART_SUCCESS`,
    CLEAR_CART_FALIURE: `CLEAR_CART_FALIURE`,

    FETCH_CART_ITEMS_START:`FETCH_CART_ITEMS_START`,
    FETCH_CART_ITEMS_SUCCESS:`FETCH_CART_ITEMS_SUCCESS`,
    FETCH_CART_ITEMS_FALIURE:`FETCH_CART_ITEMS_FALIURE`,
    IS_LOADING: `IS_LOADING`,
}

export default constants;