const constants = {
    FETCH_CATEGORIES_START: `FETCH_CATEGORIES_START`,
    FETCH_CATEGORIES_SUCCESS: `FETCH_CATEGORIES_SUCCESS`,
    FETCH_CATEGORIES_FAILURE: `FETCH_CATEGORIES_FAILURE`,

    IS_LOADING: `IS_LOADING`,
}

export default constants;