const constants = {
    FETCH_ORDERS_START: `FETCH_ORDERS_START`,
    FETCH_ORDERS_SUCCESS: `FETCH_ORDERS_SUCCESS`,
    FETCH_ORDERS_FAILURE: `FETCH_ORDERS_FAILURE`,

    CREATE_ORDER_START :`CREATE_ORDER_START`,
    CREATE_ORDER_SUCCESS :`CREATE_ORDER_SUCCESS`,
    CREATE_ORDER_FAILURE :`CREATE_ORDER_FAILURE`,

    CANCEL_ORDER_START: `CANCEL_ORDER_START`,
    CANCEL_ORDER_SUCCESS: `CANCEL_ORDER_SUCCESS`,
    CANCEL_ORDER_FAILURE: `CANCEL_ORDER_FAILURE`,

    IS_LOADING: `IS_LOADING`,
}

export default constants;