const constants = {
    FETCH_PRODUCT_LIST_START: `FETCH_PRODUCT_LIST_START`,
    FETCH_PRODUCT_LIST_SUCCESS: `FETCH_PRODUCT_LIST_SUCCESS`,
    FETCH_PRODUCT_LIST_FAILURE: `FETCH_PRODUCT_LIST_FAILURE`,

    FETCH_PRODUCT_START: `FETCH_PRODUCT_START`,
    FETCH_PRODUCT_SUCCESS: `FETCH_PRODUCT_SUCCESS`,
    FETCH_PRODUCT_FALIURE: `FETCH_PRODUCT_FALIURE`,

    FILTER_PRODUCT_START: `FILTER_PRODUCT_START`,
    FILTER_PRODUCT_SUCCESS: `FILTER_PRODUCT_SUCCESS`,
    FILTER_PRODUCT_FALIURE: `FILTER_PRODUCT_FALIURE`,

    IS_LOADING: `IS_LOADING`,
}

export default constants;